### ISSUE TITLE
Add default unit functions to variable endpoints

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSSServices#105]
- [ ] Allow user to select a default unit when creating a new variable type

- [ ] Send default unit type back when variable types requested? this would help with adding a new scenario in NSS, so the default unit would already be available

**Comment by kjacobsen16** [comment]
@fanguyc-usgs assigning you this one - the VariableUnitType table serves as a crosswalk between variable types and unit types. I think if you select the variables (rather than variable types) in the services, it includes all that. But, the variables endpoint just sends through the variable types, so just the name, code, description of the variable types. We want the default unit type id sent through as well.

Let me know if you have any questions!

**Comment by fanguyc-usgs** [comment]
We should be good to go on branch cmd-dev#105
