### ISSUE TITLE
Update NSSDB/GagesDB from latest Access Release

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/NSSServices#111]
We'll need to update our test systems to bring in the new data.

From Ryan, keeper of the SSDB:
> Hi All,
> 
> I may have missed some names on the distribution list, so feel free to forward as needed. Today's StreamStatsDB release includes a plethora of edits and updates:
> 
> 1) 172 new statlabels were added, including a suite of drainage-area-only peakflows, a suite of bankfull-width-based peakflows, a suite of active-channel-width-based peakflows, a suite of remotely-sensed-width-based peakflows, a set of PROSPERum statlabels used in Montana, a PA-specific basin slope statlabel, a suite of baseline-period duration statlabels, and a suite of drainage-area-only duration statlabels; 2) datasource ID 62 was updated and the url corrected; 3) the StatisticTypeCode for BSLDEM10ff was corrected by changing it from CHAN to TOPO; 4) selected peakflow equations in Iowa were edited to utilize the newly-created drainage-area-only suite of peakflow statlabels; 5) selected New Jersey duration equations were edited to utilize the newly-created baseflow-period statlabels; 6) selected Montana peakflow equations were edited to utilize the newly-created active-channel-width and bankfull-width peakflow statlabels; 7) the url was updated for OFR 03-263; 8) Oklahoma peakflow equations were edited & added to reflect updates in SIR 2019-5143, and a new datasource was added for it; 9) Pennsylvania peakflow equations were edited & added to reflect updates in SIR 2019-5094, and a new datasource was added; 10) corrected the region names for bankfull flows in Kentucky to reflect that they are not actually statewide equations; 11) updated the citation url for WRIR 99-4032; 12) created a new DataSource for SIR 2005-5076; 12) edited peakflow region names in Illinois using input from Tom Over, to clarify for users; 13) Duration flow equations in Illinois and Indiana were edited to utilize the newly-created drainage-area-only statlabels; 14) added two sets of custom units for springs per square mile, and for centimeters; 15) edited peakflow equations in Montana to utilize the newly-created bankfull-width and active-channel-width statlabels.
> 
> You can download it from ftp://ftpint.usgs.gov/private/er/va/reston/StreamStatsDB/ . A copy has also been placed on VM103 at D:\ss_apps\DB. This new database release is ready to be loaded onto the V4 Test web application and the Dev batch processor (https://igskbthivmss103.cr.usgs.gov/ss_bp/).
> 
> Along with this SSDB update, I will have updated region polygons for PA and OK coming on Monday.
> 
> Have a great weekend!
> Ryan

**Comment by kjacobsen16** [comment]
@jknewson let me know when you're available to go through the update process for this.

There are a few things that I've updated in the test DB as well, does the script add things on top of the existing tables, or does it completely redo the DB tables?

**Comment by jknewson** [comment]
It really depends on the table, Some tables are refreshed where others are left alone.

**Comment by kjacobsen16** [comment]
Forgot this was an open issue - NSS DB is updated
