### ISSUE TITLE
Scenarios Links "href" property is wrong

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSSServices#112]
![image](https://user-images.githubusercontent.com/35497731/78040428-07d3bf80-7335-11ea-86f2-50d96cb2bf89.png)
should say `test.streamstats.usgs.gov/citations?...`

**Comment by fanguyc-usgs** [comment]
For this example, should the href be "test.streamstats.usgs.gov/citations?regressionregions=400,401,402,403,404,405,406,407,408,409,410,411,412,413"?

**Comment by kjacobsen16** [comment]
Whoops, I missed an important part there. It should be `https://test.streamstats.usgs.gov/nssservices/citations?regressionregions=400,401,402,403,404,405,406,407,408,409,410,411,412,413` (needs the nssservices part)

You can test it out using the service doc, which for some reason requires a region, even though the request I listed above works.
https://test.streamstats.usgs.gov/docs/nssservices/#/Citations/GET/Citations

**Comment by kjacobsen16** [comment]
Reopening since it'll be changed in the same place, we should add `https://` at the beginning, right now it's just sending through as `test.streamstats.usgs.gov/nssservices...`
