### ISSUE TITLE
Add "Status" attribute to equations

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/NSSServices#114]
We will need a Status to track if an equation is available in Test, Production, or if it's been superseded.

**Comment by kjacobsen16** [comment]
Looks like issue #76 was created for this purpose:
>attribute regression regions for public availability.
Equation attributes: enabled (publicly available), disabled (Depreciated), test (private/internal)

**Comment by kjacobsen16** [comment]
need a "DateStatusModified" attribute to show when the status was changed
