### ISSUE TITLE
Issues with statusID

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSSServices#148]
- [x] When first creating a new regression region the statusID is always reset it to a statusID of 1. When editing a regression region the statusID can be set to anything and works as it should.
- [x] When creating a new scenario the following error occurs (tested on regression regions: Test KJ and KJ Test 2)[error](https://user-images.githubusercontent.com/59063181/87809510-21840e80-c821-11ea-8836-1ad6274d646f.png)

**Comment by kjacobsen16** [comment]
Note to self: Looks like there's a check in here for a citationID when creating a regression region that determines if the status ID will be 2 or 1. I'll adjust so it only does that if it's missing both a status ID and citation ID.
