### ISSUE TITLE
Edits to unit types

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSSServices#176]
- [x] Update force update script to pull unit type for each variable type and set default unit in db - there should be a unit id in the stat label table

- [x] Make default unit a field in the variable type and regression type tables rather than in the Variables table

@jknewson do you remember why the default units were added to the "Variables" table? Was there any functionality set up there that we would need to worry about?

**Comment by jknewson** [comment]
Sorry, I don't remember. I think it was mostly a temporary patch to fill the gap for basin characteristics defined in the Streamstats xml's but not used in NSS. But its been too long to recall the details and/or any dependencies etc.

**Comment by kjacobsen16** [comment]
Ok, thanks. I'll leave the existing ones then just in case and switch the functionality over. Hopefully nothing breaks, since not all variables have default units anyway 🤷
