### ISSUE TITLE
Add Scenario Modal Changes - Allow partial prediction interval 

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSSServices#179]
Remove the requirement to have every part of a prediction interval filled in

Note that we'll be changing how the pred int is input anyway, but this'll allow Ryan to test out the functionality more.

**Comment by kjacobsen16** [comment]
Notes from investigation: the prediction interval fails when the covariance matrix or xi row vectors are null/empty because it's not in the right format. I sent an email to Ryan for example values and more info so I can code around it.

**Comment by kjacobsen16** [comment]
We now have an option to skip the equation check, closing this issue for now.

Note that it also appears that most incomplete prediction intervals are actually working.
