### ISSUE TITLE
Filter statisticgroups endpoint by regression region status?

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/NSSServices#206]
I think since we query statistic groups for a region based on the available equations, we'll also want to make sure that filters based on the regression region status IDs.

For example, based on the status IDs, the production services in WV only get a scenario for the depth statistics, although based on the statisticgroups endpoint it seems like there are more. 

https://streamstats.usgs.gov/nssservices/Regions/WV/Scenarios
https://streamstats.usgs.gov/nssservices/statisticgroups?regions=WV

**Comment by kjacobsen16** [comment]
@harper-wavra This is a good first issue for you!

**Comment by harper-wavra** [comment]
https://test.streamstats.usgs.gov/nssservices/Regions/Test/Scenarios - comes back with just Flow-Duration Statistics 
https://test.streamstats.usgs.gov/nssservices/statisticgroups?regions=Test - comes back with Flow-Duration Statistics and Peak-Flow Statistics. It should only come back with Flow-Duration Statistics (regression regions have status of Review) and not Peak-Flow Statistics as regression regions have status of Deprecated.
