### ISSUE TITLE
Remove NSSServicesv2

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSSServices#235]
https://streamstats.usgs.gov/docs/nssservicesv2/

NSSservicesV2 was created when we were in progress of switching to the current version of the NSS Services. It was kept around because some things like the batch processor were hitting it. I've been keeping it up to date whenever I update the nssservices, but it should be removed at some point to avoid that extra work and any potential issues from not keeping them consistent. In order to remove it, you'll need to ensure StreamStats, NSS and the Batch Processor (ask John Guthrie) are all using just nssservices.

**Comment by harper-wavra** [comment]
- [ ] remove https://streamstats.usgs.gov/docs/nssservicesv2/ and https://test.streamstats.usgs.gov/docs/nssservicesv2/ websites.
- [ ] verify old NSSServicesV2 and NSSServices-QPPQ are removed from Dev and Test and Prod

**Comment by amedenblik** [comment]
I completed those 2 items. I think we are ready to close this issue? Feel free to close if you agree.

**Comment by amedenblik** [comment]
I think that happens with any link: https://streamstats.usgs.gov/docs/thing

I removed the entire docs/nssservicesv2 folders on AWS.
