### ISSUE TITLE
Additional get endpoints

### ISSUE THREAD

**Issue by harper-wavra** [USGS-WiM/NSSServices#251]
We need get endpoints for SSApplicationInfo and GeneralSSInformation tables in the shared DB.

**Comment by harper-wavra** [comment]
Yes those are two new tables in the shared DB. I think controllers would be fine, we just need to get the information from the tables I don't think we would ever need to edit or delete the entry's in those tables. So I think whatever would be easiest to just get the information.

The related client side part of this issue is here: https://github.com/USGS-WiM/StreamStats-Setup/issues/25.

**Comment by ChadFanguy-usgs** [comment]
Where was the documentation on onenote? Or was it somewhere else?

I need to lookup how to do an updated migration or scaffold to grab the new DB tables.

**Comment by harper-wavra** [comment]
There is some here: https://doimspp.sharepoint.com/sites/GS-UMidWIM/_layouts/OneNote.aspx?id=%2Fsites%2FGS-UMidWIM%2FShared%20Documents%2FProjects%2FStreamstats%20Ecosystem%2FKJ%27s%20Guide%20to%20StreamStats%201&wd=target%28FAQs.one%7CD8FCAEF7-3539-4FED-A0C2-5BCBE0E4F155%2FHow%20do%20I%20do%20a%20Dot%20Net%20Migration%7C8222FCAD-E732-41F6-A250-BE176E0C7D53%2F%29. I think that is all KJ left us for notes on dot net migrations.

**Comment by ChadFanguy-usgs** [comment]
Just to confirm, the tables were added to the Database from another project or manually?
Assuming yes, I need to do a database first migration so I need to find the right command, once I get it working I'll definitely document it somewhere in onenote

**Comment by harper-wavra** [comment]
They were added manually to the DB. Ryan gave me two excel sheets and I created the tables from those excel sheets.

**Comment by ChadFanguy-usgs** [comment]
What application do yall use to connect to the rds instance?
It works when in Visual Studio debugging with the credentials from keepass but pgAdmin and calling a command from command line times out.
And to confirm, it's Port 5432?

**Comment by harper-wavra** [comment]
I use navicat, and we use the RDS test credentials from keepass and port 5432.

**Comment by ChadFanguy-usgs** [comment]
I don't see the SSApplicationInfo and GeneralSSInformation tables in the shared db in test or nss-v2
![image](https://user-images.githubusercontent.com/12737515/181357390-83964edc-8f54-40d7-9deb-d55ae01a3c57.png)

**Comment by harper-wavra** [comment]
They are ApplicationInfo and GeneralInformation. Sorry I took out the SS after I wrote this issue because it seemed repetitive.

**Comment by ChadFanguy-usgs** [comment]
Adding how to under "NSSServices Migration/Scaffold"  in the linked KJ's Guide, it's kind of involved to run the scaffold to grab items then copying them to the SharedDBContext file.
It looks like I copied over the correct entries to enable access to the tables so I think I'll create a new Controller for each table since I don't think it would fit under any of the current Controllers under Shared:
![image](https://user-images.githubusercontent.com/12737515/181364322-b312e41e-bf6a-41e0-9aaf-3d524d58b316.png)

**Comment by harper-wavra** [comment]
Yes I think that sounds good to me.

**Comment by ChadFanguy-usgs** [comment]
What parameter should be used for ApplicationInfo and GeneralInformation? Neither of the tables have primary keys.
Will AppInfo be the Application? (assuming this is State abbreviation)
![image](https://user-images.githubusercontent.com/12737515/181370520-869990ae-55d0-4a59-be3b-be9d24fe1d80.png)
Will GenInfo be the State?
![image](https://user-images.githubusercontent.com/12737515/181370630-d416a98e-70d8-4476-94f1-4fec32aa468d.png)


Also, "GeneralInfomation" will need a small fix to add r "GeneralInformation" before push to production

**Comment by harper-wavra** [comment]
Yes it is a state abbreviation. I think the parameter for the ApplicationInfo table should be Application and the parameter for GeneralInformation should be State.

**Comment by ChadFanguy-usgs** [comment]
I think I've figured out how it all works so I have a question, do we want to continue using the same solution as previous?

It looks like there are the tables in Shared and to query those with GET or POST, there are Views in the "nss" schema. Those views are queried from the NSSAgent.cs file.

Personally, I think we should keep the same solution/workflow and I can document this all for the future. So I would create a View "ApplicationInfo_view" and "GeneralInformation_view" in the nss schema.

**Comment by ChadFanguy-usgs** [comment]
Views created in nss schema for ApplicationInfo and GeneralInformation for use in NSSDBContext.cs
![image](https://user-images.githubusercontent.com/12737515/181621939-36a7a641-f8d8-4c8e-b414-f62c54e0aebb.png)
