### ISSUE TITLE
Equation Test

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/NSSServices#33]
From Todd email
One of the really important (hidden) features of NSS is to test all equations in the database in one report by inputting the minimum and maximum values possible for every input variable.  Then a report can be generated that includes all possible equations with valid input variable ranges.  The purpose of this feature was to store away these exports and then repeat the "testall" procedure anytime the program had changed.  Comparing the "testall" output from the current NSS program with previous "testall" outputs would allow us to ensure that no new programming had caused unwanted changes to the computation of any of the equations.

Is this something you can include in NSSweb?  (...or maybe you already have.  I probably showed you this already and forgot.)  We would not want any graphics in the output report... just the computed values.  A simple text comparison program like WinMerge would allow me to quickly compare the outputs of the two exports and ensure that new code had not changed the computations.

**Comment by kjacobsen16** [comment]
this is a duplicate issue, removing in favor of #81
