### ISSUE TITLE
Part of Todds review - ID PeakFlow region 4_2016_5083 PK25 did not create high or low Prediction intervals

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/NSSServices#79]
Idaho  PeakFlow region 4_2016_5083 PK25 did not create high or low Prediction intervals 
the EXE calculates them as 10800 and 41600 for the interval.

![image](https://user-images.githubusercontent.com/8713714/49738601-f56bd900-fc4c-11e8-91c1-6e98160b61c0.png)

Service result is NaN

**Comment by kjacobsen16** [comment]
this is computing now
