### ISSUE TITLE
Part of Todds Review - Hydrograph plots

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/NSSServices#80]
When changing the Recurrence Interval or the Lag Time for the Hydrograph Plots, I couldn't figure out how to make the plot update in response to my new selections.  Likewise, when selecting chart options under the "More options" button, I could not figure out how to make my new options take effect.

**Comment by kjacobsen16** [comment]
Not able to replicate this issue, the plot updates as soon as a new selection is made
