### ISSUE TITLE
scale up streamstats test rds

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/NSSServices#82]
I'm trying to upload a series of multipolygons (and performing postgis functions) against the db, but I've found that the cpu peaks at 94% and shortly after my connection to the db is lost (or deadlocked). The update script continues to wait for a db response which never tends finish. Its only after watching the AWS console where I see my connection (usually only 1) switches to 0 and CPU drops that I know my script has failed. 

![image](https://user-images.githubusercontent.com/8713714/53663532-36a7cf80-3c23-11e9-9694-003dd4720803.png)

I'm guessing its because we are running a micro instance. Maybe postgis methods need extra umf under the hood??

Here is a sample of the script I'm hitting the rds with
```
with arcpy.da.SearchCursor(fc, ['shape@','GRIDCODE']) as cursor:
                    for row in cursor:                                
                        for gc in [x.strip() for x in row[1].split(',')]:
                            sql = 'UPDATE "nss"."RegressionRegions" SET "Location" = st_makevalid(st_transform(st_setsrid(ST_GeomFromGeoJSON(%s),%s),4269)) WHERE "Code" = %s;'
                            try:
                                connetion = psycopg2.connect(user="", password="", host="test.c69uuui2tzs0.us-east-1.rds.amazonaws.com",
                                                              port="5432", database="StatsDB")
                                cursor = connetion.cursor()
                                cursor.execute(sql,(json.dumps(self.geometry_to_struct(row[0])),sr, gc.upper()))
                                connetion.commit()
                                cursor.close()
                            except (Exception, psycopg2.DatabaseError) as error:
                                    print(error)
                            finally:
                                if connetion is not None:
                                    connetion.close()
                                                     
                        #next gc
                    #next row
                #end with
```

**Comment by aaronstephenson** [comment]
I upgraded it to db.t2.medium (2 CPU, 4 GB RAM). Let me know how that works for you and we can adjust if necessary.

**Comment by jknewson** [comment]
Working a ton better,
![image](https://user-images.githubusercontent.com/8713714/53665708-72459800-3c29-11e9-9a8d-09c865142c5e.png)
