### ISSUE TITLE
New OH equations are failing to compu

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/NSSServices#91]
It appears (at a broad stroke) the equations are failing to compute. I don't see any issue at first glance with the equations, 

inputs
Peak_Flow_Full_Model Region
Drainage Area = 36.5 (mi2)
Ohio Region C Indicator 1 if in C else 0 = 0 (dim)
Ohio Region A Indicator 1 if in A else 0 = 1 (dim)
Stream Slope 10 and 85 Longest Flow Path = 7.38 (ft/mi)
Percent Storage from NLCD1992 = 0.32 (%)
(taken from SS for location 40.42384, -83.48238)

**Comment by kjacobsen16** [comment]
Looks like this was fixed, all these equations are working
