### ISSUE TITLE
(+10)^something failing

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/NSSServices#96]
newer equations for OH peakflows fail to compute (+10)^(2.1238+0.1825*(OHREGA)+0.4098*(OHREGC))*(DRNAREA)^(0.6718)

older equations where (+10) are later in the equation compute,
50.4*(DRNAREA)^(0.777)*(CSL1085LFP)^(0.13)*(LC92STOR+1)^(-0.187)*(+10)^(0.36054*(OHREGC))*(+10)^(0.15168*(OHREGA))

Although the answer may not be accurate.

**Comment by kjacobsen16** [comment]
Looks like this was fixed by removing the the `+` and `()`

The first equation now shows up as:
`10^(2.1238+0.1825*(OHREGA)+0.4098*(OHREGC))*(DRNAREA)^(0.6718)`
